# Generated by Django 4.1.3 on 2022-12-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedbacks_delete_bookproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='phone',
        ),
    ]
