# Generated by Django 4.1.3 on 2022-12-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_feedbacks_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FeedBacks',
        ),
    ]
