# Generated by Django 4.1.3 on 2022-12-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookproject_delete_feedbacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookProject',
            new_name='Book_Project',
        ),
    ]
