# Generated by Django 4.1.3 on 2022-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_bookproject_book_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_project',
            name='phone',
            field=models.IntegerField(default=88777788),
        ),
    ]
