# Generated by Django 4.1.3 on 2022-12-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_book_project_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_project',
            name='phone',
        ),
    ]
