# Generated by Django 4.1.3 on 2022-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_book_project_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_project',
            name='phone',
            field=models.IntegerField(default=88777788),
        ),
    ]
