# Generated by Django 4.1.3 on 2022-12-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_project_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
