# Generated by Django 4.1.3 on 2022-12-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_project',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
